// Generated by gencpp from file sai_roslab/scan_range.msg
// DO NOT EDIT!


#ifndef SAI_ROSLAB_MESSAGE_SCAN_RANGE_H
#define SAI_ROSLAB_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sai_roslab
{
template <class ContainerAllocator>
struct scan_range_
{
  typedef scan_range_<ContainerAllocator> Type;

  scan_range_()
    : header()
    , closest_point(0.0)
    , farthest_point(0.0)  {
    }
  scan_range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , closest_point(0.0)
    , farthest_point(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _closest_point_type;
  _closest_point_type closest_point;

   typedef double _farthest_point_type;
  _farthest_point_type farthest_point;





  typedef boost::shared_ptr< ::sai_roslab::scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sai_roslab::scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct scan_range_

typedef ::sai_roslab::scan_range_<std::allocator<void> > scan_range;

typedef boost::shared_ptr< ::sai_roslab::scan_range > scan_rangePtr;
typedef boost::shared_ptr< ::sai_roslab::scan_range const> scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sai_roslab::scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sai_roslab::scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sai_roslab

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'sai_roslab': ['/home/sg/sai_ws/src/sai_roslab/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sai_roslab::scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sai_roslab::scan_range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sai_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sai_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sai_roslab::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sai_roslab::scan_range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sai_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "492e98f4ad5413e40d76ac2fceece9f6";
  }

  static const char* value(const ::sai_roslab::scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x492e98f4ad5413e4ULL;
  static const uint64_t static_value2 = 0x0d76ac2fceece9f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::sai_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sai_roslab/scan_range";
  }

  static const char* value(const ::sai_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sai_roslab::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 closest_point\n"
"float64 farthest_point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sai_roslab::scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sai_roslab::scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.closest_point);
      stream.next(m.farthest_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sai_roslab::scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sai_roslab::scan_range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "closest_point: ";
    Printer<double>::stream(s, indent + "  ", v.closest_point);
    s << indent << "farthest_point: ";
    Printer<double>::stream(s, indent + "  ", v.farthest_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAI_ROSLAB_MESSAGE_SCAN_RANGE_H
